tabs:
  main:
    display: Settings
    sections:
      -
        fields:
          -
            handle: enabled
            field:
              type: toggle
              display: Enabled
              instructions: "Enable or disable field encryption."
              default: true
              width: 50
